# Configuración de RBAC (Control de Acceso Basado en Roles)
# Este archivo define los permisos de acceso para la aplicación
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wiz-app-admin
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  # VULNERABILIDAD: Se asigna el rol cluster-admin, que tiene acceso completo al clúster
  # En producción, debería usar un rol con permisos mínimos necesarios
  name: cluster-admin 