# Configuración de secretos para la aplicación
# Este archivo define los secretos utilizados por la aplicación
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
stringData:
  # VULNERABILIDAD: Credenciales de MongoDB almacenadas en texto plano
  # En producción, deberían estar cifradas o usar un servicio de gestión de secretos
  MONGO_URI: "mongodb://<USER>:<PASS>@<MONGO_HOST>:27017/db" 