apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiz-app
  labels:
    app: wiz-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wiz-app
  template:
    metadata:
      labels:
        app: wiz-app
    spec:
      # Run container as root (cluster admin privileges)
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      containers:
        - name: wiz-app
          image: ${ECR_URL}:latest
          ports:
            - containerPort: 8080
          env:
            - name: MONGODB_URI
              value: "mongodb://${MONGO_IP}:27017/wizdb"
            - name: FLASK_DEBUG
              value: "1"
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "250m"
              memory: "128Mi" 