apiVersion: v1
kind: Service
metadata:
  name: wiz-app-service
  labels:
    app: wiz-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: wiz-app 