name: CI App
on:
  # Comentado para ejecución manual únicamente
  #push:
  #  paths:
  #    - 'app/**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      
      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: wiz-app
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cd app
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7 # O la versión que estés usando
      
      - name: Terraform Init
        run: terraform init
        working-directory: infra
      
      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig --name wiz-cluster-new --region us-east-1
      
      - name: Set Output Env Vars
        id: vars
        working-directory: infra 
        run: |
          echo "Getting raw outputs..."
          # Obtener outputs crudos directamente
          MONGO_IP=$(terraform output -raw mongo_public_ip)
          ECR_URL=$(terraform output -raw ecr_repository_url)
          
          # Verificar valores extraídos
          echo "Extracted MONGO_IP: [$MONGO_IP]"
          echo "Extracted ECR_URL: [$ECR_URL]"
          
          # Escribir en GITHUB_ENV
          echo "MONGO_IP=$MONGO_IP" >> $GITHUB_ENV
          echo "ECR_URL=$ECR_URL" >> $GITHUB_ENV
          echo "Wrote values to GITHUB_ENV"
      
      - name: Deploy to EKS
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          export KUBECONFIG="$HOME/.kube/config"
          
          echo "KUBECONFIG=$KUBECONFIG"
          echo "--- Kubeconfig contents ---"
          cat $KUBECONFIG || echo "Kubeconfig file not found or unreadable"
          echo "--- End Kubeconfig ---"
          
          cd app/k8s
          
          echo "Valor de ECR_URL antes de sed: [$ECR_URL]"
          echo "Valor de MONGO_IP antes de sed: [$MONGO_IP]"
          
          sed -i "s|\${ECR_URL}|${ECR_URL}|g; s|\${MONGO_IP}|${MONGO_IP}|g" *.yaml
          
          echo "--- Contenido deployment.yaml después de sed ---"
          cat deployment.yaml || echo "Error leyendo deployment.yaml"
          echo "--- Fin deployment.yaml ---"
          
          kubectl apply -f . --validate=false
          kubectl rollout status deployment/wiz-app