name: CI App
on:
  # Comentado para ejecución manual únicamente
  #push:
  #  paths:
  #    - 'app/**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      
      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: wiz-app
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cd app
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7 # O la versión que estés usando
      
      - name: Terraform Init
        run: terraform init
        working-directory: infra
      
      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig --name wiz-cluster-new --region us-east-1
      
      - name: Get MongoDB IP and ECR URL
        id: get-vars
        run: |
          cd infra
          echo "::set-output name=mongo_ip::$(terraform output -raw mongo_public_ip)"
          echo "::set-output name=ecr_url::$(terraform output -raw ecr_repository_url)"
      
      - name: Deploy to EKS
        env:
          IMAGE_TAG: ${{ github.sha }}
          MONGO_IP: ${{ steps.get-vars.outputs.mongo_ip }}
          ECR_URL: ${{ steps.get-vars.outputs.ecr_url }}
          KUBECONFIG: "${{ env.HOME }}/.kube/config"
        run: |
          cd app/k8s
          # Reemplazar variables en los manifiestos
          sed -i "s|\${ECR_URL}|${ECR_URL}|g; s|\${MONGO_IP}|${MONGO_IP}|g" *.yaml
          # Aplicar los manifiestos (desactivando validación)
          kubectl apply -f . --validate=false
          # Verificar el despliegue
          kubectl rollout status deployment/wiz-app