name: CI Infra
on:
  workflow_dispatch:
  # Comentado para ejecución manual únicamente
  #push:
  #  paths:
  #    - 'infra/**'
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform Init
        run: terraform init -backend-config="bucket=wiz-exercise-terraform-state" 
        working-directory: infra
      - name: Terraform Validate
        run: terraform validate
        working-directory: infra

      # Añadir paso para importar la entrada de acceso existente (si existe)
      # Esto sincroniza el estado si la entrada ya fue creada por un recurso anterior
      - name: Terraform Import EKS Access Entry
        run: |
          terraform import aws_eks_access_entry.interactive_user wiz-cluster-new:arn:aws:iam::277707137984:user/odl_user_1695962 || echo "Import failed, maybe entry doesn't exist yet. Continuing..."
          terraform import aws_eks_access_policy_association.interactive_user_admin wiz-cluster-new#arn:aws:iam::277707137984:user/odl_user_1695962#arn:aws:eks::aws:cluster-access-policy/AmazonEKSClusterAdminPolicy || echo "Import failed, maybe association doesn't exist yet. Continuing..."
        working-directory: infra

      - name: Terraform Plan
        run: terraform plan
        working-directory: infra
      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: infra